version: '3.8'

services:
  rails:
    build: .
    command: >
      /bin/sh -c "rails db:migrate && rails r lib/scripts/create_bots.rb && puma -C config/puma.rb"
    env_file:
      - config.env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./config/master.key:/rails-api/config/master.key
      - ./config/ssl:/rails-api/config/ssl

  db:
    image: postgres:latest
    env_file:
      - config.env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  sidekiq:
    build: .
    command: >
      /bin/sh -c "sleep 20 && bundle exec sidekiq -C config/sidekiq.yml"
    env_file:
      - config.env
    depends_on:
      - redis
      - rails
    volumes:
      - ./config/master.key:/rails-api/config/master.key
      - ./config/ssl:/rails-api/config/ssl
