default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost'%>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  database: <%= ENV['POSTGRES_DB'] || 'myapi'%>

test:
  <<: *default
  database: testdb

production:
  <<: *default
  database: productiondb
  username: my_production_user
  password: <%= ENV['MY_PRODUCTION_DATABASE_PASSWORD'] %>

